version: '2'

networks:

  demo-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"


services:
  postgresdb:
    image: busybox
    volumes:
      - /var/lib/postgresql/data

  postgres:
  #  name: postgres
    image: sameersbn/postgresql:9.5-2
    hostname: postgres
    volumes_from:
      - postgresdb
    ports:
     - "5432:5432"
    environment:
      PG_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq
    #hostname: rabbitmq
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
     - "25672:25672"
     - "5671:5671"
     - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret

  discovery:
    image: "discovery:1.0.0-SNAPSHOT"
    hostname: discovery
  #  name: discovery
    environment:
      EUREKA_HOST: discovery2
      EUREKA_PORT: 8762
      DISCOVERY_SERVER_PORT: 8761
    ports:
     - "8761:8761"

  discovery2:
    image: "discovery:1.0.0-SNAPSHOT"
    hostname: discovery2
  #  name: discovery
    links:
      - discovery
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      DISCOVERY_SERVER_PORT: 8762
    ports:
     - "8762:8762"

  eureka-client:
    image: "eureka-client:1.0.0-SNAPSHOT"
    hostname: eureka-client
  #  name: config
    depends_on:
      - discovery
      - discovery2
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "9090:9090"

  config:
    image: "config:1.0.0-SNAPSHOT"
    hostname: config
  #  name: config
    depends_on:
      - discovery
      - discovery2
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "8888:8888"

  api-gateway:
    image: "api-gateway:1.0.0-SNAPSHOT"
    hostname: api-gateway
  #  name: config
    depends_on:
      - discovery
      - discovery2
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "5555:5555"

  person:
    image: person:1.0.0-SNAPSHOT
    hostname: person
    depends_on:
      - discovery
      - discovery2
      - config
      - postgres
      - rabbitmq
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"

  person2:
    image: person:1.0.0-SNAPSHOT
    mem_limit: 1000000000
    hostname: person2
    depends_on:
      - discovery
      - discovery2
      - config
      - person
      - postgres
      - rabbitmq
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
       PERSON_SERVER_PORT: 8081
       PERSON_DDL_AUTO: none
    ports:
      - "8081:8081"

  some:
    image: some:1.0.0-SNAPSHOT
    hostname: some
    depends_on:
      - discovery
      - discovery2
      - config
      - rabbitmq
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"

  some2:
    image: some:1.0.0-SNAPSHOT
    hostname: some2
    depends_on:
      - discovery
      - discovery2
      - config
      - rabbitmq
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
       SOME_SERVER_PORT: 8084
    ports:
      - "8084:8084"

  ui:
    image: ui:1.0.0-SNAPSHOT
    hostname: ui
    depends_on:
      - discovery
      - discovery2
      - config
      - person
      - some
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "801:801"

  monitor:
    image: monitor:1.0.0-SNAPSHOT
    hostname: monitor
    depends_on:
      - discovery
      - discovery2
      - config
      - person
      - some
      - ui
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8989:8989"

  zipkin-server:
    image: zipkin-server:1.0.0-SNAPSHOT
    #hostname: monitor
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    restart: always