version: '2'

networks:

  demo-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"


services:

  elasticsearch:
    image: elasticsearch
    networks:
      - demo-net
    container_name: elasticsearch
    volumes:
      - /opt/springboot/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: logstash
    networks:
      - demo-net
    hostname: logstash
    container_name: logstash
    command: logstash -e 'input { udp { port => 4560 codec => json } } output { elasticsearch { hosts => "elasticsearch:9200" } }'
    ports:
      - 4560:4560/udp
    depends_on:
      - elasticsearch

  kibana:
    image: kibana
    networks:
      - demo-net
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  postgresdb:
    image: busybox
    networks:
      - demo-net
    volumes:
      - /var/lib/postgresql/data

  postgres:
  #  name: postgres
    image: sameersbn/postgresql:9.5-2
    networks:
      - demo-net
    hostname: postgres
    volumes_from:
      - postgresdb
    ports:
     - "5432:5432"
    environment:
      PG_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq
    networks:
      - demo-net
    #hostname: rabbitmq
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
     - "25672:25672"
     - "5671:5671"
     - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: secret

  discovery:
    image: "discovery:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: discovery
  #  name: discovery
    environment:
      EUREKA_HOST: discovery2
      EUREKA_PORT: 8762
      DISCOVERY_SERVER_PORT: 8761
    ports:
     - "8761:8761"

  discovery2:
    image: "discovery:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: discovery2
  #  name: discovery
    links:
      - discovery
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      DISCOVERY_SERVER_PORT: 8762
    ports:
     - "8762:8762"

  eureka-client:
    image: "eureka-client:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: eureka-client
  #  name: config
    depends_on:
      - discovery
      - discovery2
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "9090:9090"

  config:
    image: "config:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: config
  #  name: config
    depends_on:
      - discovery
      - discovery2
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       CONFIG_SERVER_PORT: 8888
    ports:
      - "8888:8888"

  config2:
    image: "config:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: config2
  #  name: config
    depends_on:
      - discovery
      - discovery2
      - config
    environment:
      EUREKA_HOST: discovery
      EUREKA_PORT: 8761
      CONFIG_SERVER_PORT: 8889
    ports:
      - "8889:8889"

  api-gateway:
    image: "api-gateway:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: api-gateway
  #  name: config
    depends_on:
      - discovery
      - discovery2
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
    ports:
      - "5555:5555"

  api-gateway2:
    image: "api-gateway:1.0.0-SNAPSHOT"
    networks:
      - demo-net
    hostname: api-gateway2
  #  name: config
    depends_on:
      - discovery
      - discovery2
      - api-gateway
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       GATEWAY_SERVER_PORT: 5556
    ports:
      - "5556:5556"

  person:
    image: person:1.0.0-SNAPSHOT
    networks:
      - demo-net
    hostname: person
    depends_on:
      - discovery
      - discovery2
      - config
      - config2
      - postgres
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"

  person2:
    image: person:1.0.0-SNAPSHOT
    networks:
      - demo-net
    mem_limit: 1000000000
    hostname: person2
    depends_on:
      - discovery
      - discovery2
      - config
      - config2
      - person
      - postgres
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
       PERSON_SERVER_PORT: 8081
       PERSON_DDL_AUTO: none
    ports:
      - "8081:8081"

  some:
    image: some:1.0.0-SNAPSHOT
    networks:
      - demo-net
    hostname: some
    depends_on:
      - discovery
      - discovery2
      - config
      - config2
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"

  some2:
    image: some:1.0.0-SNAPSHOT
    networks:
      - demo-net
    hostname: some2
    depends_on:
      - discovery
      - discovery2
      - config
      - config2
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
       SOME_SERVER_PORT: 8084
    ports:
      - "8084:8084"

  ui:
    image: ui:1.0.0-SNAPSHOT
    networks:
      - demo-net
    hostname: ui
    depends_on:
      - discovery
      - discovery2
      - config
      - config2
      - api-gateway
      - api-gateway2
      - person
      - some
      - rabbitmq
      - logstash
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "801:801"

  monitor:
    image: monitor:1.0.0-SNAPSHOT
    networks:
      - demo-net
    hostname: monitor
    depends_on:
      - discovery
      - discovery2
      - config
      - config2
      - person
      - some
      - ui
    environment:
       EUREKA_HOST: discovery
       EUREKA_PORT: 8761
       SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8989:8989"

  zipkin-server:
    image: zipkin-server:1.0.0-SNAPSHOT
    networks:
      - demo-net
    #hostname: monitor
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    restart: always