server:
  port: ${person.server.port:8082}
 

spring:
  jpa:
    hibernate:
      ddl-auto: ${person.ddl.auto:update}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: secret
  sleuth:
    sampler:
      percentage: 1