server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: true
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
  client:
    register-with-eureka: false
    fetch-registry: false
    